basic.forever(function () {
    basic.showNumber(pins.analogReadPin(AnalogPin.P0))
    basic.clearScreen()
    basic.pause(500)
    basic.showNumber(pins.analogReadPin(AnalogPin.P1))
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.Square)
    basic.clearScreen()
    basic.showIcon(IconNames.Scissors)
    pins.analogWritePin(AnalogPin.P9, Math.map(50, 0, 100, 0, 1023))
    pins.analogSetPeriod(AnalogPin.P9, 1000)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P9, Math.map(0, 0, 100, 0, 1023))
    basic.clearScreen()
})
